function _fzf_configure_bindings_help
    echo 'fzf_configure_bindings - change the key bindings for fzf.fish.'
    echo 'Usage:'
    echo '    fzf_configure_bindings [--SEARCHABLE_ENTITY[=KEY_SEQUENCE]...]'
    echo 'Description:'
    echo '    Without any options, fzf_configure_bindings installs the default key bindings. Options override or disable default bindings.'
    echo '    Key bindings must be specified as long options where the option name is an entity searchable by fzf.fish and the option value is a key sequence. Try fish_key_reader to generate key sequences.'
    echo '    Fails if provided positional arguments or unknown options.'
    echo '    Completely overwrites any fzf.fish bindings previously installed by this function. This means users are free to repeatedly invoke this function to experiment with different bindings without having to worry about residual bindings.'
    echo 'Options:'
    echo '    --directory=key_sequence'
    echo '    --git_log=key_sequence'
    echo '    --git_status=key_sequence'
    echo '    --history=key_sequence'
    echo '    --variables=key_sequence'
    echo '    -h or --help'
end
